timeout: 10
verbose: yes
serial: yes
/PureC OS 64-bit Limine+GOP (primary)
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/boot/kernel-fallback.elf
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_path: boot():/bin/init
    module_path: boot():/bin/installer
    module_path: boot():/bin/snake
    module_path: boot():/bin/tetris
    module_path: boot():/bin/program/terminal
    module_path: boot():/bin/program/nano
    module_path: boot():/bin/program/system
    module_path: boot():/bin/program/files
    module_path: boot():/bin/program/settings
    module_path: boot():/bin/program/monitor
    module_path: boot():/bin/program/disks
    module_path: boot():/bin/program/logview
    module_path: boot():/bin/program/hexedit
    module_path: boot():/bin/program/tetris
    module_path: boot():/bin/gui-demo
    module_path: boot():/bin/modules/ext2.elf
    module_path: boot():/lib/libpurec.a
    module_path: boot():/lib/libpuregui.a
    module_path: boot():/lib/libpguiw.a
    module_path: boot():/lib/libpurefs.a
    module_path: boot():/include/puregui.h
    module_path: boot():/include/pguiw.h
    module_path: boot():/include/purefs.h
/PureC OS 64-bit (fallback previous image)
    protocol: limine
    kernel_path: boot():/boot/kernel-fallback.elf
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_path: boot():/bin/init
    module_path: boot():/bin/installer
    module_path: boot():/bin/snake
    module_path: boot():/bin/tetris
    module_path: boot():/bin/program/terminal
    module_path: boot():/bin/program/nano
    module_path: boot():/bin/program/system
    module_path: boot():/bin/program/files
    module_path: boot():/bin/program/settings
    module_path: boot():/bin/program/monitor
    module_path: boot():/bin/program/disks
    module_path: boot():/bin/program/logview
    module_path: boot():/bin/program/hexedit
    module_path: boot():/bin/program/tetris
    module_path: boot():/bin/gui-demo
    module_path: boot():/lib/libpurec.a
    module_path: boot():/lib/libpuregui.a
    module_path: boot():/lib/libpguiw.a
    module_path: boot():/lib/libpurefs.a
    module_path: boot():/include/puregui.h
    module_path: boot():/include/pguiw.h
    module_path: boot():/include/purefs.h
